### ISSUE TITLE
Osnova - Úvod do strojového učení 

### ISSUE THREAD

**Issue by PetraVidnerova** [PyDataCZ/naucse.python.cz#10]
nástřel 
https://docs.google.com/document/d/1rKfo21NWsDfRSHhpWgsnuSwLbbk7ZAX97HT5KsYsw1Q/edit?usp=sharing

kritika a připomínky jsou velice žádoucí

**Comment by janpipek** [comment]
Mně se to líbí.

**Comment by PetraVidnerova** [comment]
Kdyby měl někdo nápad na nějaký pěkný data, tak sem s nima. Já asi kouknu na různý tutoriály, co se kde používá. Může být i klasifikace (ale řeklo se, že ne obrázky). pak se vezmou klasifikační metriky, a věci kolem regrese se udělají v další hodině s lineární regresí.

**Comment by coobas** [comment]
Pěkné :)

út 15. 10. 2019 v 9:11 odesílatel PetraVidnerova <notifications@github.com>
napsal:

**Comment by PetraVidnerova** [comment]
Na posledním Pyvu mi někdo (vím, kdo, ale  mám špatnou pamět na jména :disappointed: ) říkal, že má nějaké nápady na data. Pospíchala jsem už pryč, ale připomínám, urguju, zájem o data trvá ...

**Comment by AndrejSvitek** [comment]
Dobrovoľne sa priznávam, že som to bol ja. Minulý týždeň som mal v Prahe rodinu zo Slovenska, takže som nakoniec nič nestihol, ako som plánoval.

Idem sa na tie dáta vrhnúť práve teraz.

**Comment by AndrejSvitek** [comment]
Takže, ak vynechám také tie prefláknuté datasety typu Titanic, Boston Housing, Iris, MNIST... tak som pracoval s:

**Telcom Customer Churn** - [Kaggle link](https://www.kaggle.com/blastchar/telco-customer-churn)
Klasifikácia odchádzajúcich zákazníkov pre telekomunikačnú spoločnosť. Tento dataset poznám najlepšie a je to pre mňa najlepšia ukážka ML v praxi, kde je okrem modelovania nutné riešiť aj biznisový zmysel.

Zaujalo ma:
* Pomerne ľahko pochopiteľný a celkom aktuálny.
* Banky a telekomunikačné spoločnosti churn (odchod zákazníkov) riešia v praxi často.
* Dáta treba trocha očistiť (0,1 % chýbajúcich hodnôt) a transformovať.
* Nevybalansované triedy (26 % churn vs 74 % non-churn), takže treba správne samplovať.
* Veľmi dobre sa dá demonštrovať, ako ho typické metriky (accuracy, recall, precision, F-score, ROC) výsledok skresľujú a nie sú pre tieto dáta úplne najvhodnejšie.
* Pre optimálne výsledky je nutné správne nastaviť decision threshold pre model (to je ale asi už mimo osnovy)

**Diamond Prices** - [Kaggle link](https://www.kaggle.com/shivam2503/diamonds)
Regresia, predikcia ceny diamantov na základe ich charakteristík. Na Kaggle je k tomu kernel aj s obrázkami, že ako vyzerajú jednotlivé rezy, ako sa hodnotia farebné odtiene atď., takže aspoň pre mňa to bolo celkom zábavné s tým pracovať.

Zaujalo ma:
* Dobre pochopiteľné, čo jednotlivé stĺpce znamenajú.
* Treba základne očistiť dáta (pár nezmyselných hodnôt).
* Obsahuje aj kategorické, aj numerické dáta.
* Bez aplikovania numerického škálovania menej robustné modely dávajú úplne nezmyselné výsledky.

**New York City Airbnb Open Data** - [Kaggle link](https://www.kaggle.com/dgomonov/new-york-city-airbnb-open-data)
Regresia, predikcia cien Airbnb na základe charakteristík. Dáta z roku 2019.

Zaujalo ma:
* Veľká variabilita vstupných dát (numerické, kategorické, geografická poloha, hodnotenie vo forme textu...)
* Menej robustné regresné modely zle znášajú skosené rozdelenie cieľovej premennej (cena), takže je z nej lepšie odstrániť outliers a logaritmicky transformovať.
* Airbnb reálne takýto model má vyvinutý, ktorý na základe zadaných údajov odporúča cenu.

**Standford How Couples Meet and Stay Together** - [Standford link](https://data.stanford.edu/hcmst2017)
Popravde nie až tak vhodný dataset na ML, ale nesmierne zaujímavý pohľad na to, ako sa v priebehu času mení stretávanie ľudí a názory na to, čo zabezpečuje šťastné vzťahy. Náročnejší dataset (cca 250 stĺpcov), ale zase veľmi dobre odráža to, aké datasety v realite sú.

**Bosch Production Line Performance** - [Kaggle link](https://www.kaggle.com/c/bosch-production-line-performance)
Klasifikácia chybných produktov na výrobnej linke.

Typické dáta pre automotive, takže úplný hnus a radšej by som zožral žabu ako s tými dátami pracovať. Ale keby sme chceli niekoho potrestať...

**Predikcia web trafficu, finančné trhy** - časové rady som v osnove nevidel, tak vynechávam.

**Comment by AndrejSvitek** [comment]
Keďže nemôžem @PetraVidnerova napísať napriamo na Slacku, tak keby si k tými dátami potom chcela nejak pomôcť, tak rád pridám pomocnú ruku.

**Comment by PetraVidnerova** [comment]
@AndrejSvitek dala jsem na Slacku testovací zprávu, zdá se, že to lze :)

**Comment by janpipek** [comment]
Materiály jsou již hotovy a učilo se podle nich.
