### ISSUE TITLE
Osnova: Analýza hlavních komponent (PCA)

### ISSUE THREAD

**Issue by simecek** [PyDataCZ/naucse.python.cz#12]
https://docs.google.com/document/d/1oa-V9V8_5Bglb5gDl0dbW3jO4BrdMauNprIe7MCn4mk/edit?usp=sharing

(omlouvám se za zpoždění)

**Comment by PetraVidnerova** [comment]
Díky moc, Verču to trošku vyděsilo (doufám, že se nebude zlobit, že to píšu, ale její pohled je taky potřeba), mě to tak hrozné nepřijde. Nějaké poznámky tedy píšu do toho.

**Comment by veronikks** [comment]
Přiznávám, že na první pohled mne trochu vyděsila ta teorie, ale článek o tom, jak to vysvětlit i babičce, mne trochu uklidnil :-) Obecně mi to na dvě hodiny přijde docela obsáhlé, ale tématu nerozumím, takže komentáře k obsahu přenechám jiným. Za sebe bych se jen přimluvila za omezení matematiky na nutné minimum, jak kvůli publiku, tak kvůli omezenému času. Skvělá práce, díky moc!

**Comment by AndrejSvitek** [comment]
Myslím si, že obsah je v poriadku, ale bude to klásť celkom nároky na prednášajúceho na to vedieť vysvetliť tú matematiku tak, aby tomu každý pochopil. Čo v Peťovom prípade určite problém nebude, ale čo ak ho niekto bude musieť zastúpiť.

Takže by som sa tiež prihováral ku úplnému minimu matematiky a vynechaniu LDA, t-SNE... Po 2 hodinách machine learningu podľa mňa budeme úplne štastní, keď účastníci budú vedieť vysvetliť rozdiel medzi klasifikáciou a regresiou.

Za mňa by mi úplne stačilo, keby som si z tej hodiny odniesol, že niekedy chceme znížiť počet charakteristík ale nechceme ich odstrániť úplne, tak máme na to nástroj a trocha rozumiem princípu, ako funguje.

Ináč super Peťo, teraz sa ma niekto na PCA pýtal, tak asi ho potom odkážem na tvoj materiál :-)

**Comment by janpipek** [comment]
Mně se to líbí.

Jinak se snahou tam mít málo matematiky celkem souhlasím.

**Comment by coobas** [comment]
Díky, pěkné :)

čt 24. 10. 2019 v 21:29 odesílatel Jan Pipek <notifications@github.com>
napsal:

**Comment by PetraVidnerova** [comment]
> Za mňa by mi úplne stačilo, keby som si z tej hodiny odniesol, že niekedy chceme znížiť počet 
> charakteristík ale nechceme ich odstrániť úplne, tak máme na to nástroj a trocha rozumiem princípu, 
> ako funguje.

Tohle naprosto vystihuje i můj názor a myslím, že je to i to, co se tak dá za jednu lekci stihnout.

Jinak ta osnova obsahově super, jen eliminovat tu teorii a asi snížit množství.

**Comment by frenzymadness** [comment]
Kdy je v plánu k tomuto připravit materiály?

**Comment by janpipek** [comment]
Materiály jsou již hotovy a učilo se podle nich.
