### ISSUE TITLE
Osnova: API

### ISSUE THREAD

**Issue by dakarabas** [PyDataCZ/naucse.python.cz#13]
https://docs.google.com/document/d/1978F5l7WGOOT7_MIk7iDFYiS5ia1AmeB9qcjhKyI8uQ/edit

**Comment by coobas** [comment]
Jelikož téma se mi zdá lehčí než např. PCA apod., otevírá se víc možností pro hands-on během hodiny - třeba nějaký miniprojekt který bude tahat data z různých API a něco pěkného s nimi dělat.  Cy myslíte?

**Comment by janpipek** [comment]
Mně se to líbí.

**Comment by PetraVidnerova** [comment]
Je to hezké, konečně nějaká lekce, která snad půjde v klidu stihnout za tu dvouhodinovku. 
Jediné co k tomu mám, je to celé o JSON, mělo by se říct, že mohou být i jiné formáty. Případně zkusit jak JSON, tak něco jiného?

**Comment by dakarabas** [comment]
Ano, chtěl bych to pojmout spíš prakticky, úvod bude krátký...že by si vytahly něco z nějakého API, zchroupaly ho a vyplivly tabulku/graf. O jiných formáte řeknu a můžeme prvně exrahovat něco jiného, ale s jinými formáty se bude pracovat při jiných hodinách, tak bych spíš chtěl pracovat hlavně s tím JSONem

**Comment by janpipek** [comment]
Materiály jsou již hotovy a učilo se podle nich.
