### ISSUE TITLE
Osnovy: EDA

### ISSUE THREAD

**Issue by janpipek** [PyDataCZ/naucse.python.cz#14]
Nedokázali jsme se úplně shodnout na koncepci. My s Kubou jsme to chtěli víc technické (hlavně porozumění pandas) a Lumír víc statistické. A tak máme osnovy hned dvě:

"Ostravská varianta" - https://docs.google.com/document/d/1o-AygnmxMLb3bf3QAnUBcyj9qBSeIg5LFB2ADYx5Zto/

"Pražská varianta" - https://docs.google.com/document/d/1_xwmis5HFsz-WQVjdzIA4c_1w7pEIFmEvAAiGY3MpCs/

(omluva za zpoždění by tu měla být více než dvojnásobná, jen Lumír svou část odevzdal včas).

**Comment by coobas** [comment]
Já se přidávám k té omluvě ...

**Comment by simecek** [comment]
Já se přidávám s omluvou - za opožděné komentáře. Osobně by mne asi víc láká pražská varianta (bojím se, že nematematicky podaná statistika nebude dostatečně zajímavá a užitečná). Ale chápu i smysl ostravské - třeba přírodovědcům by se tohle myslím líbilo.

**Comment by janpipek** [comment]
Zavírám, koncepce obou variant kurzu jsou asi jasné.
