### ISSUE TITLE
Deploy do produkce

### ISSUE THREAD

**Issue by frenzymadness** [PyDataCZ/naucse.python.cz#27]
Deploy konkrétního kurzu na produkční naučse vypadá tak, že se zde ve forku ve složce např. `runs/2020/pydata-ostrava-jaro/` vytvoří soubor s obsahem kurzu - např. [takto](https://github.com/PyLadiesCZ/naucse.python.cz/blob/autumn2019/runs/2019/pyladies-ostrava-podzim/info.yml).

Do [hlavního repa](https://github.com/pyvec/naucse.python.cz/) se pak vytvoří soubor odkazující na tento fork a konkrétní branch - např. [takto](https://github.com/pyvec/naucse.python.cz/blob/master/runs/2019/pyladies-ostrava-podzim/link.yml).

Výhodou je, že běžícím či už minulým kurzům se nemění obsah, protože ten je v konkrétním branchi pro konkrétní běh a nehýbe se s ním, pokud to není nezbytně nutné.

Proto navrhuji:
1. tvořit dále materiály v mastru
2. zhruba v polovině ledna vytvořit branch `spring2020` z masteru a do něj připravit obsah obou jarních kurzů (s tím, co bude v té době k dispozici).
3. Dále po domluvě do nového branche z mastru mergovat změny a nové materiály, které budou mít pro první běh smysl. Klidně hromadně skrze PR, pokud to bude dávat smysl.

Jde mi hlavně o to, aby bylo jasné, co patří kam a aby se nasazení do produkce udělalo/otestovalo včas.

Dává to smysl?

**Comment by janpipek** [comment]
Asi v zásadě souhlas. Termín půlka ledna je dobrá, zejména pokud by půlka znamenala 16. ledna, což je přesně týden před ostrým startem pražského kurzu.

**Comment by frenzymadness** [comment]
Startujeme nebo je merge otevřených PR v dohledu?

**Comment by janpipek** [comment]
Co se týče větví, vytvořil bych dvě (když budou stejné, tak to nebude vadit). Asi umíme natolik nakládat s gitem, abychom si přimergovali vždy to, co je potřeba. Naopak se vyhneme nutnosti si to mezi sebou navzájem schvalovat a překvapení, kdyby se nějaký materiál najednou změnil pod rukama.

Run bych založil rád dnes nebo zítra, ale chce to ještě drobné dodělávky do EDA 1,2 a vytvořit yaml.

Poznámka: ještě jsem nestudoval, jak fungují webhooks, ale hodlám to dostudovat...

**Comment by frenzymadness** [comment]
Myslím si, že workflow i nasazování do produkce máme vyřešeno ke spokojenosti. Po kurzech mergneme změny do masteru a můžeme začít nanovo.
