### ISSUE TITLE
Pandas profiling

### ISSUE THREAD

**Issue by frenzymadness** [PyDataCZ/naucse.python.cz#28]
Chceme napsat krátký samostatný materiál (asi v MD) o pandas profiling, který bude společný pro obě verze EDA?

Dokážu si představit, že by to mohlo být jako bonusový materiál, který se vytáhne ve chvíli, kdy na to zbude čas nebo když se objeví dotaz na něco podobného.

**Comment by coobas** [comment]
No asi proč ne. Asi se (aspoň zatím) nehlásím k psaní - jednak kvůli práci na EDA a jednak kvůli tomu že nejsem v pandas profiling až tak zběhlý.

**Comment by janpipek** [comment]
Za mě taky nic proti.

**Comment by frenzymadness** [comment]
Fixed in https://github.com/PyDataCZ/naucse.python.cz/commit/2e5a4dbaa6d239ba5a0948270b7822375cf655a1
