### ISSUE TITLE
Conda vs pip

### ISSUE THREAD

**Issue by frenzymadness** [PyDataCZ/naucse.python.cz#7]
Používat v materiálech pro instalaci condu, pip nebo oboje? Z dosavadních zkušeností funguje pip ve virtuálním prostředí dobře, ale s pokročilejšími nástroji (NN, scikit-learn, …) může nastat problém se ne-python závislostmi.

**Comment by kokes** [comment]
Jsem pro pip ze tří důvodů:

1. Je to vestavěná část Pythonu, je to základní věc.
2. Je to součástí předchozích kurzů
3. Conda řešila problémy, který pip z velký části (ne úplně) vyřešil wheelama, tak mi to přijde zbytečné ukazovat externí package manager

ALE, napřed bych vyzkoušel, že všechno v našem kurzu funguje s pipem. (Od dob wheelů jsem s pipem nikdy problém neměl, ani se scikitem, tensorflow atd., tak jsem zvědav, jestli se něco objeví.)

**Comment by janpipek** [comment]
Pro největší balíčky (včetně sciki-learn) `pip`určitě problém není. Spousta věcí ale binární distribuci nemá a může být pain-in-the-[cl]ass je instalovat, zejména v multiplatformním prostředí.

Ale je možné, že na ně mám jenom smůlu (např. že chci používat `line_profiler` a že mi ho gcc odmítá zkompilovat).

**Comment by coobas** [comment]
Jeden důvod proč bych chtěl condu minimálně zmínit je, že se vyskutuje v mnoha dalších materiálech a spoustakrát jsem se setkal s dotazy typu co je pip / conda / anaconda atp. Druhý je, že pokud bude někdo pracovat ve Windows, tak s pipem dřív nebo později (spíš dřív) narazí na komplikaci s instalací nějakého balíčku.

**Comment by janpipek** [comment]
Condu jsme zmínili, ale v materiálech preferujeme pip.
