### ISSUE TITLE
[EDA Praha] Stahování dat — requests vs urllib

### ISSUE THREAD

**Issue by frenzymadness** [PyDataCZ/naucse.python.cz#80]
Všiml jsem si, že v rámci pražské EDA se stahují data pomocí `urllib`, ale zbytek kurzu (API, WebScraping, Databáze) používají `requests`. Možná by stálo za to to sjednotit.

**Comment by janpipek** [comment]
Upraveno na requests:

- [x] EDA 2
- [x] EDA 3

**Comment by janpipek** [comment]
A právě jsem to opravil ve větvi pro úpravy EDA 4. Tímto z EDA Praha urllib zmizela...
