### ISSUE TITLE
Osnova: Web scraping

### ISSUE THREAD

**Issue by karlafej** [PyDataCZ/naucse.python.cz#9]
https://docs.google.com/document/d/1cN8aITFg8glXct-Olp_pZI52s-MrWaDninG8adLkaCo/edit?usp=sharing

**Comment by janpipek** [comment]
Mně se to líbí.

**Comment by kokes** [comment]
Chybí mi tam trochu ta lidská stránka věci. Osobně vnímám scraping jako hodně šedou praktiku, tak bych nerad, aby to lidi brali jako normální věc, kterou budou dělat ve velkym.

**Comment by frenzymadness** [comment]
Jako příklad pro tuto hodinu by mohlo posloužit parsování informací o krajskýcch městech z Wikipedie. Těch stránek je jen 13, jejich URL se dá odvodit přímo z názvu města a tabulka se základními informacemi v pravém sloupci každé stránky ma celkem jednotnou strukturu. No a nakonec by mohlo zaznít ponaučení, že než se pustíme do parsování, je třeba hledat jiné zdroje, což v tomto případě nebude tak složité.

**Comment by karlafej** [comment]
Díky, to je dobrý nápad!

**Comment by janpipek** [comment]
Materiály jsou již hotovy a učilo se podle nich.
